### ISSUE TITLE
[Reference] References

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/zulu#14]
I hope that these references help to develop [zulu](https://github.com/DE-labtory/zulu).

If you have any reference to share, please comment or edit this.

### Golang, Development
- [Article) The best Golang Web Frameworks](https://medium.com/devtechtoday/top-7-golang-web-frameworks-in-2020-and-beyond-9ca2a89eb904)
- [Article) 왜 JSON-RPC를 사용할까? (Ko)](https://getoutsidedoor.com/2019/08/10/%EC%99%9C-json-rpc%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C/)

### Blockchain API
- [Docs) Rosetta Node API](https://docs.ont.io/developer-tools/api/rosetta-node-api#submit-a-signed-transaction)
- [Docs) Rosetta API Docs](https://www.rosetta-api.org/docs/welcome.html)
- [Repo) Rosetta SDK in Go](https://github.com/coinbase/rosetta-sdk-go)

### Ethereum
- [Book) Go Ethereum Book](https://goethereumbook.org/en/)
- [Repo) Go Ethereum](https://github.com/ethereum/go-ethereum)

### Bitcoin
- [Repo) Bitcoin in Go](https://github.com/btcsuite)
- [Lecture) Bitcoin Lesson - Script](https://www.youtube.com/watch?v=6Fa04MnURhw)
- [Lecture) Bitcoin Lesson - Transaction](https://www.youtube.com/watch?v=Shd9nXe1X-0)

### Wallet, Key, Sign
- [Article) 코드체인과 HD Wallet (Ko)](https://medium.com/codechain-kr/%EC%BD%94%EB%93%9C%EC%B2%B4%EC%9D%B8%EA%B3%BC-hd-wallet-d7a9e120794f)
- [Docs) BIP-0032 Specification: Key derivation](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Specification_Key_derivation)

**Comment by baumstern** [comment]
#### General

* [Wallet Best Practices - Mastering Ethereum](https://github.com/ethereumbook/ethereumbook/blob/develop/05wallets.asciidoc#wallet-best-practices)

#### BTC wallet
* https://github.com/square/beancounter: a command line utility to audit the balance of Hierarchical Deterministic (HD) wallets written in Go

**Comment by AgwaB** [comment]
**ETHEREUM**
- https://goethereumbook.org/en/
