### ISSUE TITLE
[Test] Does client using blockchain node need to mock?

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/zulu#54]
We hide our blockchain node endpoints. So, we could not test using CI. 

If it is necessary to test `DeriveAccount()`, we should query balance value of that account from blockchain.
But, CI doesn't know our blockchain endpoint. So, it should be failed.

Then, how can we success CI test? Should I test using mock for client?

I'll expect your awesome idea!

**Comment by junbeomlee** [comment]
You can test by hiding the endpoint from the outside by using the secret of the travis ci.

**Comment by junbeomlee** [comment]
https://travis-ci.com/github/DE-labtory/zulu/settings
