### ISSUE TITLE
[Proposal] Signer interface & Relevant architecture

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/zulu#7]
![zulu](https://user-images.githubusercontent.com/20393677/87869579-df52fc80-c9db-11ea-93f6-dba9e62f539a.png)

signer 관련 interface, 함수들과 관련된 컴포넌트들 흐름따라서 전체적으로 그려봤어요

코드 참고하기 편하게 그려놓은거라 나중에 최종본 정리해서 올릴게여 참고용으로 봐주세요

**Comment by AgwaB** [comment]
지금 이 구조에는 DB상으로 Wallet이랑 Key가 분리되어 있는데 제 생각에는 Wallet이라는 하나의 DB로 가는게 좋을거 같아요. 개념상으로 key가 wallet의 아래이고, db도 key-value db 쓸거니까 단순하게 가는게 좋지 않나 싶음.

**Comment by hihiboss** [comment]
`key store` 컴포넌트에 key 저장하는 DB가 (@AgwaB 의견으로 따르면 wallet DB가) 구현되고
`signer` 컴포넌트에 sign/verify 로직 구현되고
`key chain`에서 `key store`의 key 가져다가 `signer`의 sign/verify 을 이용하는 식으로 돼야하지않나 생각합니당!

지금 그림은 key들이 signer/verifier 밑에 있어서 `key store`가 singer랑 verifier 밑에 각각 구현되는 느낌이 들어요!

그리고 adapter가 txbuilder랑 keychain 사용하고 있어서 txbuilder-keychain 연관은 굳이 필요없어도 될듯??

--
**UPDATE**
아 key가 singer 구현체네 @.@

제 생각 정리해보면 이렇게 이해했습니다.
|#2 컴포넌트 | @hea9549 그림|
|---|---|
|signer|key|
|key store|pair store + wallet store|
|key chain|key chain|

결국 저도 @AgwaB 의견으로 수렴하는듯..

그리고 또 하나! signer랑 verifier 따로 구분한 이유있나여??

**Comment by hea9549** [comment]
이거 진행하면서 정리했던 생각이,
Signer, Verifier가 꼭 PubKey, PrvKey의 비대칭 키쌍이 아닌, 싸이닝과, 증명만 해주는 interface로 최대한 추상화했슴니당

Signing을 해주는 주체가 Secp256k1 커브를 이용한 private key가 직접 해줄수도있고, remote server 로 분리되어 Signing을 위임할수 있고, 예를들어 KMS같은 곳이 Signing을 담당해줄 수 있습니다.

키와같은 경우는 Signer가 Verifier를 알아낼 수 있는 구조지만, 일반적인 구성을 위해 signer와 verifier를 아예 키와 분리하고 PairStore 에서 공통 id로 쌍으로 접근하게끔 해두었습니다, 각각은 자기가 할일만 맡아서 하구요~  -> 구현체 자체는 자기의일만 딱 하게끔 분리를해두었습니다.

그래서 Keystore이란말이 조금 어색해서 PairStore로 나타냈슴니다.

-> 일있어서 쫌따 이어씀

**Comment by baumstern** [comment]
전체적인 플로우를 나름대로 생각해봤는데 여기에 있는 아키텍처랑 거의 비슷하더라고요. 가령 별도의 KMS나 하드웨어 월렛을 사용하는 유즈 케이스를 생각해보니 txbuilder가 signing interface에 서명을 요청하는 방식이 알맞다고 생각했습니다.
(wallet id와 coin type을 이용해서 특정한 개인키를 찾는다는 유즈 케이스를 생각했을 때) persistence store는 다른 분들 의견처럼 wallet DB 하나로도 충분할 것 같아요.
